language: c
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - build_main_platforms
  - arduino --verify --board arduino:avr:uno $PWD/examples/BasicNode/BasicNode.ino
notifications:
  email:
    on_success: change
    on_failure: change
